### ISSUE TITLE
Refactor config to use Neon

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/monarch#5]
I believe that Nette's [NEON](https://doc.nette.org/en/neon) config language provides quite a few benefits and a great user experience. Update our config system to use NEON, keeping the currently usability.

**Comment by lonnieezell** [comment]
Looking a little closer and I don't think this is possible. I cannot find any way to include environment variables in the config format. I found a closed issue on their DI where [they were discussing ](https://github.com/nette/di/issues/8)using `getenv` but that's all I found. 

So unless someone can point me how to do this, I think I'm scrapping this idea.

**Comment by eydun** [comment]
The neon-package (https://ne-on.org) does not per default use variables. 
But in Nette it is possible to use parameters for config-files with the bootstrap-package (https://doc.nette.org/en/application/bootstrap).
Phpstan uses neon-format for configuration, and has built something for supporting environmental variables.

In Nette you usually have multiple config files, and in some cases two different files for production and development environments (e.g. local.neon for database-config).
